### ISSUE TITLE
bug: model can't be loaded on linux mint 20.3 (version `GLIBC_2.32' not found)

### ISSUE THREAD

**Issue by kristaller486** [janhq/jan#1187]
**Describe the bug**
Model can't be loaded because nitro won't started

**To Reproduce**
I just tried loading the model on Linux Mint 20.3

**Expected behavior**
Model is loaded

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3 x86_64
 - GPU: GT740
 - RAM: 16GB
 - CPU: i5-4460
 - Version 0.4.3

**Additional context**
traceback:

```bash
Start requesting to kill Nitro...
Nitro is killed
Starting Nitro subprocess...
stdout: Selected GPU: 0

subprocess error:./nitro: error while loading shared libraries: libcudart.so.12: cannot open shared object file: No such file or directory

stderr: ./nitro: error while loading shared libraries: libcudart.so.12: cannot open shared object file: No such file or directory

stdout: nitro_linux_amd64_cuda encountered an error, attempting to run nitro_linux_amd64...

subprocess error:./nitro: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./nitro)
./nitro: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./nitro)
./nitro: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./nitro)
./nitro: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./nitro)
./nitro: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./nitro)

stderr: ./nitro: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./nitro)
./nitro: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./nitro)
./nitro: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./nitro)
./nitro: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./nitro)
./nitro: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./nitro)

child process exited with code 1
error:  child process exited with code 1
```

**Comment by tikikun** [comment]
@hiento09 we might not be able to statically link glibc, we might need to support multiple version build

**Comment by hiento09** [comment]
Hi @kristaller486 , please try our newest Nightly Build version [here](https://github.com/janhq/jan) to check if this bug is resolved or not. From now we support glibc >= 2.27 (ubuntu 18.04 or higher).

**Comment by kristaller486** [comment]
@hiento09, sorry for the late reply, I didn't have access to my linux pc. I have now checked 0.4.3-135 and it still doesn't work.

```bash
Starting Nitro subprocess...
subprocess error:/home/developer/jan/extensions/@janhq/inference-nitro-extension/dist/bin/linux-cpu/nitro: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/developer/jan/extensions/@janhq/inference-nitro-extension/dist/bin/linux-cpu/nitro)
/home/developer/jan/extensions/@janhq/inference-nitro-extension/dist/bin/linux-cpu/nitro: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/developer/jan/extensions/@janhq/inference-nitro-extension/dist/bin/linux-cpu/nitro)
/home/developer/jan/extensions/@janhq/inference-nitro-extension/dist/bin/linux-cpu/nitro: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /home/developer/jan/extensions/@janhq/inference-nitro-extension/dist/bin/linux-cpu/nitro)

stderr: /home/developer/jan/extensions/@janhq/inference-nitro-extension/dist/bin/linux-cpu/nitro: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/developer/jan/extensions/@janhq/inference-nitro-extension/dist/bin/linux-cpu/nitro)
/home/developer/jan/extensions/@janhq/inference-nitro-extension/dist/bin/linux-cpu/nitro: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/developer/jan/extensions/@janhq/inference-nitro-extension/dist/bin/linux-cpu/nitro)
/home/developer/jan/extensions/@janhq/inference-nitro-extension/dist/bin/linux-cpu/nitro: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /home/developer/jan/extensions/@janhq/inference-nitro-extension/dist/bin/linux-cpu/nitro)
```

**Comment by hiento09** [comment]
@kristaller486 , can you follow this instruction to install g++11 since it's requirements for linux https://jan.ai/guides/troubleshooting/gpu-not-used/#specific-requirements-for-linux

**Comment by kristaller486** [comment]
Thanks for your help, it's all working now

**Comment by lampinap** [comment]
I have glibc 2.28 on rocky and am getting a version issue with cortex needing 2.29.
