### ISSUE TITLE
bug: Jan is not using GPU

### ISSUE THREAD

**Issue by x51don** [janhq/jan#1385]
**Describe the bug**
Looks like Jan is using only CPU, and it is very slow. GMP utilization is 7% on average.

**Steps to reproduce**
normal operation

**Expected behavior**
to see GPU utilization and work faster

**Environment details**
- Operating System: PoPOS!
- Jan Version: 4.3
- Processor: Intel i7-9750H
- RAM: 16GB
- Any additional relevant hardware specifics: Nvidia GTX 1050

**Comment by guennibear** [comment]
Same behavior on Windows 11
No usage of GPU
Very slow response

Environment details
Operating System: Windows 11
Jan Version: 4.3
Processor: Intel i9-13900K
RAM: 128GB
GPU: Nvidia RTX 4090, RTX 3090TI

**Comment by 0xSage** [comment]
We weren't propagating CUDA issues in the old build. 

Can you check: 
1. Cuda is downloaded
2. Try the latest release to see any other errors: https://github.com/janhq/jan?tab=readme-ov-file#download

**Comment by guennibear** [comment]
Working after I did reinstall the latest CUDA Toolkit. Seems my old Cuda install was broken

**Comment by x51don** [comment]
> By default, we enable GPU acceleration.
> 
> If you are experiencing this issue, you may need to download the latest Nvidia CUDA toolkit and turn on the setting to enable Nvidia GPU acceleration. We weren't propagating CUDA issues in the old build.
> 
> Steps:
> 
> 1. Download Cuda toolkit (v11.4+): https://developer.nvidia.com/cuda-downloads?target_os=Windows
> 2. Try the latest release to see any other errors: https://github.com/janhq/jan?tab=readme-ov-file#download
> 
> @hieu-jan to translate this into docs 🙏

Reinstalled CUDA, but didn't helped. (I'm using also stable-diffusion for image generation and it is utilizing GPU normally)

**Comment by pbeens** [comment]
Installing the Cuda toolkit worked for me. Interestingly I'm not always seeing an improvement in many cases.

**Comment by 0xSage** [comment]
> d CUDA, but didn't helped. (I'm using also stable-dif

Do you see more RAM available like this:
<img width="827" alt="image" src="https://github.com/janhq/jan/assets/69952136/7db41492-c749-4632-9061-28e4ea56c4be">

**Comment by x51don** [comment]
> > d CUDA, but didn't helped. (I'm using also stable-dif
> 
> Do you see more RAM available like this: <img alt="image" width="827" src="https://private-user-images.githubusercontent.com/69952136/294645213-7db41492-c749-4632-9061-28e4ea56c4be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MzE4MTUsIm5iZiI6MTcwNDUzMTUxNSwicGF0aCI6Ii82OTk1MjEzNi8yOTQ2NDUyMTMtN2RiNDE0OTItYzc0OS00NjMyLTkwNjEtMjhlNGVhNTZjNGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA4NTgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MzYzMzFkNmE5MDM2MTEyYzRhZDhmZjc0ZDVjZTBmODEyMjAxZjhmMmI4OGY3ZjZjYzE4MWVmNzdhMzhhNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kJ8DmJKU5EerKN10A59zw1zrOYvXU7IU-NWWBred4G0">

![image](https://github.com/janhq/jan/assets/90650239/e3f7d94c-b6da-4a47-bdbe-68ac702179b5)

**Comment by lunisahdidouch** [comment]
I have the same issue but have a 6700 xt. It is supposed to be supported as far as I know. Do I have to do something else with an AMD gpu? Also have 100% cpu usage and no gpu usage.

RAM: 32gb DDR4 3200Mhz.
CPU: i5 11400
GPU: 6700 xt
SSD: 2tb Kingston fury renegade ssd
OS: Windows 10

**Comment by lunisahdidouch** [comment]
I have the same issue but have a 6700 xt. It is supposed to be supported as far as I know. Do I have to do something else with an AMD gpu? Also have 100% cpu usage and no gpu usage.

RAM: 32gb DDR4 3200Mhz.
CPU: i5 11400
GPU: 6700 xt
SSD: 2tb kingston fury renegade ssd.

**Comment by Hxitech** [comment]
I have the same issue with RTX 4070. Tried re-install CUDA, re-install Jan, and the nightly build. 
RAM: 32GB DDR4
CPU: i7-12700
GPU: RTX 4070 12GB
OS: Windows 11
Jan version: 0.4.3

**Comment by hiento09** [comment]
Hi guys, could you please try our nightly build version available at this link: https://github.com/janhq/jan?tab=readme-ov-file#download, to check if it resolves the issue? Thank you.

**Comment by hiento09** [comment]
We don't have the GPU detection feature in version 0.4.3 yet. It has only been enabled in the nightly build version. This feature will be officially available in Jan's release 0.4.4.

**Comment by Hxitech** [comment]
@hiento09 The nightly build does solve the issue.

Thanks!! Looking forward to seeing the 0.4.4 release!

**Comment by x51don** [comment]
> We don't have the GPU detection feature in version 0.4.3 yet. It has only been enabled in the nightly build version. This feature will be officially available in Jan's release 0.4.4.

on Night version I have error: 
![image](https://github.com/janhq/jan/assets/90650239/5284ccad-abc4-4be5-b328-ba63b793ad14)

**Comment by lunisahdidouch** [comment]
> We don't have the GPU detection feature in version 0.4.3 yet. It has only been enabled in the nightly build version. This feature will be officially available in Jan's release 0.4.4.
@hiento09

Should this also work for AMD gpu's? Because I do see the option saying "Enable GPU acceleration for NVidia GPU's", but nothing for AMD GPU's. My CPU is still being used rather than my GPU (6700 xt). Or is the GPU detection feature supposed to be working and I wouldn't have to change anything manually? Because then the feature isn't working in my case.

**Comment by hiento09** [comment]
Hi @lunisahdidouch , we have added a feature to support AMD GPU, you can check it here https://github.com/janhq/jan/issues/1608. Thank you for spending your time with Jan App.

**Comment by Ciela2002** [comment]
I'm commenting on this a lots of time after.. it's seem to restart lagging. Jan was using my gpu before. Now when i try to run somes model like CodeNinja it just dont work. I've try to uninstall and re install cuda etc nothing seem to work :((

Specs: 
I5 12400F
4060 8G
48G ddr4 3200

**Comment by Ciela2002** [comment]
I found the problem, never activate Vulkan even if you do it accidentally and you deactivate it it corrupts the CUDA files. I had to uninstall Jan, then cuda, then reboot my pc and uninstall all the nvidia drivers and then I reinstalled them all and now they all work.

**Comment by marvelsanya** [comment]
The same problem: the application does not use the GPU at all, instead it loads the CPU and, if it produces a response from the models, it is after a very long time. In addition, enabling NVIDIA GPU acceleration in the application settings does not produce results and if enabled, it does not launch any model at all.

(sorry bad english)

**Comment by Hubert21** [comment]
I do have the same problem, as described in #6780,
my GPU is barely not used ; instead the CPU is running 100%, even with a small model that does not take all the VRAM

RAM: 16gb 
CPU: i5 2500
GPU: 2060 RTX (6 GB)
OS: Windows 10
Nvidia Driver Version: 581.29
CUDA Version: 13.0
