### ISSUE TITLE
bug: Can't start model with GPU acceleration enabled

### ISSUE THREAD

**Issue by oleole39** [janhq/jan#4417]
### Jan version

0.5.13

### Describe the Bug

Hello,

Model would manage to start only if GPU acceleration is disabled.

Log shows `ERROR ggml_backend_cuda_buffer_type_alloc_buffer: allocating 1018.00 MiB on device 0: cudaMalloc failed: out of memory` even though GPU has 2GB VRAM.

Machine has:
- NVIDIA GPU with 2GB VRAM
- NVIDIA Driver Version: 550.120
- CUDA Version: 12.4
- OS: LinuxMint 21 (Ubuntu 22.04-based)
- Jan: 0.5.13 (deb) and 0.5.7 (Appimage)
- Model: Llama 3.2 1B Instruct Q8 (had tested 1 or 2 other models earlier with the same result).

### Logs

<details><summary>Unfold cortex.log (Jan 0.5.13)</summary>

```log
20250107 23:31:26.880605 UTC 902738 INFO  Number of parallel is set to 4 - llama_engine.cc:604
20250107 23:31:26.880653 UTC 902738 INFO  system info: {'n_thread': 8, 'total_threads': 8. 'system_info': 'CUDA : ARCHS = 520,610,700,750 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | LLAMAFILE = 1 | OPENMP = 1 | AARCH64_REPACK = 1 | CUDA : ARCHS = 520,610,700,750 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | LLAMAFILE = 1 | OPENMP = 1 | AARCH64_REPACK = 1 | CUDA : ARCHS = 520,610,700,750 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | LLAMAFILE = 1 | OPENMP = 1 | AARCH64_REPACK = 1 | '} - llama_engine.cc:680
20250107 23:31:26.880728 UTC 902738 INFO  llama_load_model_from_file: using device CUDA0 (NVIDIA {MODEL}) - 1955 MiB free
 - llama_engine.cc:523
20250107 23:31:26.914664 UTC 902738 INFO  llama_model_loader: loaded meta data with 35 key-value pairs and 147 tensors from /MY_AI_MODELS_PATH/Llama-3.2-1B-Instruct-Q8_0.gguf (version GGUF V3 (latest))
 - llama_engine.cc:523
20250107 23:31:26.914698 UTC 902738 INFO  llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
 - llama_engine.cc:523
20250107 23:31:26.914706 UTC 902738 INFO  llama_model_loader: - kv   0:                       general.architecture str              = llama
 - llama_engine.cc:523
20250107 23:31:26.914712 UTC 902738 INFO  llama_model_loader: - kv   1:                               general.type str              = model
 - llama_engine.cc:523
20250107 23:31:26.914717 UTC 902738 INFO  llama_model_loader: - kv   2:                               general.name str              = Llama 3.2 1B Instruct
 - llama_engine.cc:523
20250107 23:31:26.914722 UTC 902738 INFO  llama_model_loader: - kv   3:                           general.finetune str              = Instruct
 - llama_engine.cc:523
20250107 23:31:26.914727 UTC 902738 INFO  llama_model_loader: - kv   4:                           general.basename str              = Llama-3.2
 - llama_engine.cc:523
20250107 23:31:26.914732 UTC 902738 INFO  llama_model_loader: - kv   5:                         general.size_label str              = 1B
 - llama_engine.cc:523
20250107 23:31:26.914737 UTC 902738 INFO  llama_model_loader: - kv   6:                            general.license str              = llama3.2
 - llama_engine.cc:523
20250107 23:31:26.914748 UTC 902738 INFO  llama_model_loader: - kv   7:                               general.tags arr[str,6]       = ["facebook", "meta", "pytorch", "llam...
 - llama_engine.cc:523
20250107 23:31:26.914756 UTC 902738 INFO  llama_model_loader: - kv   8:                          general.languages arr[str,8]       = ["en", "de", "fr", "it", "pt", "hi", ...
 - llama_engine.cc:523
20250107 23:31:26.914761 UTC 902738 INFO  llama_model_loader: - kv   9:                          llama.block_count u32              = 16
 - llama_engine.cc:523
20250107 23:31:26.914767 UTC 902738 INFO  llama_model_loader: - kv  10:                       llama.context_length u32              = 131072
 - llama_engine.cc:523
20250107 23:31:26.914772 UTC 902738 INFO  llama_model_loader: - kv  11:                     llama.embedding_length u32              = 2048
 - llama_engine.cc:523
20250107 23:31:26.914777 UTC 902738 INFO  llama_model_loader: - kv  12:                  llama.feed_forward_length u32              = 8192
 - llama_engine.cc:523
20250107 23:31:26.914782 UTC 902738 INFO  llama_model_loader: - kv  13:                 llama.attention.head_count u32              = 32
 - llama_engine.cc:523
20250107 23:31:26.914787 UTC 902738 INFO  llama_model_loader: - kv  14:              llama.attention.head_count_kv u32              = 8
 - llama_engine.cc:523
20250107 23:31:26.914795 UTC 902738 INFO  llama_model_loader: - kv  15:                       llama.rope.freq_base f32              = 500000.000000
 - llama_engine.cc:523
20250107 23:31:26.914809 UTC 902738 INFO  llama_model_loader: - kv  16:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
 - llama_engine.cc:523
20250107 23:31:26.914814 UTC 902738 INFO  llama_model_loader: - kv  17:                 llama.attention.key_length u32              = 64
 - llama_engine.cc:523
20250107 23:31:26.914819 UTC 902738 INFO  llama_model_loader: - kv  18:               llama.attention.value_length u32              = 64
 - llama_engine.cc:523
20250107 23:31:26.914824 UTC 902738 INFO  llama_model_loader: - kv  19:                          general.file_type u32              = 7
 - llama_engine.cc:523
20250107 23:31:26.914829 UTC 902738 INFO  llama_model_loader: - kv  20:                           llama.vocab_size u32              = 128256
 - llama_engine.cc:523
20250107 23:31:26.914834 UTC 902738 INFO  llama_model_loader: - kv  21:                 llama.rope.dimension_count u32              = 64
 - llama_engine.cc:523
20250107 23:31:26.914839 UTC 902738 INFO  llama_model_loader: - kv  22:                       tokenizer.ggml.model str              = gpt2
 - llama_engine.cc:523
20250107 23:31:26.914844 UTC 902738 INFO  llama_model_loader: - kv  23:                         tokenizer.ggml.pre str              = llama-bpe
 - llama_engine.cc:523
20250107 23:31:26.929936 UTC 902738 INFO  llama_model_loader: - kv  24:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
 - llama_engine.cc:523
20250107 23:31:26.944535 UTC 902738 INFO  llama_model_loader: - kv  25:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
 - llama_engine.cc:523
20250107 23:31:26.982389 UTC 902738 INFO  llama_model_loader: - kv  26:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
 - llama_engine.cc:523
20250107 23:31:26.982428 UTC 902738 INFO  llama_model_loader: - kv  27:                tokenizer.ggml.bos_token_id u32              = 128000
 - llama_engine.cc:523
20250107 23:31:26.982438 UTC 902738 INFO  llama_model_loader: - kv  28:                tokenizer.ggml.eos_token_id u32              = 128009
 - llama_engine.cc:523
20250107 23:31:26.982451 UTC 902738 INFO  llama_model_loader: - kv  29:                    tokenizer.chat_template str              = {{- bos_token }}\n{%- if custom_tools ...
 - llama_engine.cc:523
20250107 23:31:26.982460 UTC 902738 INFO  llama_model_loader: - kv  30:               general.quantization_version u32              = 2
 - llama_engine.cc:523
20250107 23:31:26.982471 UTC 902738 INFO  llama_model_loader: - kv  31:                      quantize.imatrix.file str              = /models_out/Llama-3.2-1B-Instruct-GGU...
 - llama_engine.cc:523
20250107 23:31:26.982481 UTC 902738 INFO  llama_model_loader: - kv  32:                   quantize.imatrix.dataset str              = /training_dir/calibration_datav3.txt
 - llama_engine.cc:523
20250107 23:31:26.982490 UTC 902738 INFO  llama_model_loader: - kv  33:             quantize.imatrix.entries_count i32              = 112
 - llama_engine.cc:523
20250107 23:31:26.982499 UTC 902738 INFO  llama_model_loader: - kv  34:              quantize.imatrix.chunks_count i32              = 125
 - llama_engine.cc:523
20250107 23:31:26.982507 UTC 902738 INFO  llama_model_loader: - type  f32:   34 tensors
 - llama_engine.cc:523
20250107 23:31:26.982516 UTC 902738 INFO  llama_model_loader: - type q8_0:  113 tensors
 - llama_engine.cc:523
20250107 23:31:27.355416 UTC 902738 INFO  llm_load_vocab: special tokens cache size = 256
 - llama_engine.cc:523
20250107 23:31:27.401836 UTC 902738 INFO  llm_load_vocab: token to piece cache size = 0.7999 MB
 - llama_engine.cc:523
20250107 23:31:27.401875 UTC 902738 INFO  llm_load_print_meta: format           = GGUF V3 (latest)
 - llama_engine.cc:523
20250107 23:31:27.401880 UTC 902738 INFO  llm_load_print_meta: arch             = llama
 - llama_engine.cc:523
20250107 23:31:27.401892 UTC 902738 INFO  llm_load_print_meta: vocab type       = BPE
 - llama_engine.cc:523
20250107 23:31:27.401897 UTC 902738 INFO  llm_load_print_meta: n_vocab          = 128256
 - llama_engine.cc:523
20250107 23:31:27.401901 UTC 902738 INFO  llm_load_print_meta: n_merges         = 280147
 - llama_engine.cc:523
20250107 23:31:27.401905 UTC 902738 INFO  llm_load_print_meta: vocab_only       = 0
 - llama_engine.cc:523
20250107 23:31:27.401910 UTC 902738 INFO  llm_load_print_meta: n_ctx_train      = 131072
 - llama_engine.cc:523
20250107 23:31:27.401914 UTC 902738 INFO  llm_load_print_meta: n_embd           = 2048
 - llama_engine.cc:523
20250107 23:31:27.401918 UTC 902738 INFO  llm_load_print_meta: n_layer          = 16
 - llama_engine.cc:523
20250107 23:31:27.401925 UTC 902738 INFO  llm_load_print_meta: n_head           = 32
 - llama_engine.cc:523
20250107 23:31:27.401931 UTC 902738 INFO  llm_load_print_meta: n_head_kv        = 8
 - llama_engine.cc:523
20250107 23:31:27.401935 UTC 902738 INFO  llm_load_print_meta: n_rot            = 64
 - llama_engine.cc:523
20250107 23:31:27.401939 UTC 902738 INFO  llm_load_print_meta: n_swa            = 0
 - llama_engine.cc:523
20250107 23:31:27.401943 UTC 902738 INFO  llm_load_print_meta: n_embd_head_k    = 64
 - llama_engine.cc:523
20250107 23:31:27.401947 UTC 902738 INFO  llm_load_print_meta: n_embd_head_v    = 64
 - llama_engine.cc:523
20250107 23:31:27.401952 UTC 902738 INFO  llm_load_print_meta: n_gqa            = 4
 - llama_engine.cc:523
20250107 23:31:27.401957 UTC 902738 INFO  llm_load_print_meta: n_embd_k_gqa     = 512
 - llama_engine.cc:523
20250107 23:31:27.401962 UTC 902738 INFO  llm_load_print_meta: n_embd_v_gqa     = 512
 - llama_engine.cc:523
20250107 23:31:27.401966 UTC 902738 INFO  llm_load_print_meta: f_norm_eps       = 0.0e+00
 - llama_engine.cc:523
20250107 23:31:27.401971 UTC 902738 INFO  llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
 - llama_engine.cc:523
20250107 23:31:27.401976 UTC 902738 INFO  llm_load_print_meta: f_clamp_kqv      = 0.0e+00
 - llama_engine.cc:523
20250107 23:31:27.401980 UTC 902738 INFO  llm_load_print_meta: f_max_alibi_bias = 0.0e+00
 - llama_engine.cc:523
20250107 23:31:27.401984 UTC 902738 INFO  llm_load_print_meta: f_logit_scale    = 0.0e+00
 - llama_engine.cc:523
20250107 23:31:27.401989 UTC 902738 INFO  llm_load_print_meta: n_ff             = 8192
 - llama_engine.cc:523
20250107 23:31:27.401993 UTC 902738 INFO  llm_load_print_meta: n_expert         = 0
 - llama_engine.cc:523
20250107 23:31:27.401998 UTC 902738 INFO  llm_load_print_meta: n_expert_used    = 0
 - llama_engine.cc:523
20250107 23:31:27.402002 UTC 902738 INFO  llm_load_print_meta: causal attn      = 1
 - llama_engine.cc:523
20250107 23:31:27.402006 UTC 902738 INFO  llm_load_print_meta: pooling type     = 0
 - llama_engine.cc:523
20250107 23:31:27.402010 UTC 902738 INFO  llm_load_print_meta: rope type        = 0
 - llama_engine.cc:523
20250107 23:31:27.402014 UTC 902738 INFO  llm_load_print_meta: rope scaling     = linear
 - llama_engine.cc:523
20250107 23:31:27.402020 UTC 902738 INFO  llm_load_print_meta: freq_base_train  = 500000.0
 - llama_engine.cc:523
20250107 23:31:27.402024 UTC 902738 INFO  llm_load_print_meta: freq_scale_train = 1
 - llama_engine.cc:523
20250107 23:31:27.402028 UTC 902738 INFO  llm_load_print_meta: n_ctx_orig_yarn  = 131072
 - llama_engine.cc:523
20250107 23:31:27.402033 UTC 902738 INFO  llm_load_print_meta: rope_finetuned   = unknown
 - llama_engine.cc:523
20250107 23:31:27.402037 UTC 902738 INFO  llm_load_print_meta: ssm_d_conv       = 0
 - llama_engine.cc:523
20250107 23:31:27.402041 UTC 902738 INFO  llm_load_print_meta: ssm_d_inner      = 0
 - llama_engine.cc:523
20250107 23:31:27.402045 UTC 902738 INFO  llm_load_print_meta: ssm_d_state      = 0
 - llama_engine.cc:523
20250107 23:31:27.402050 UTC 902738 INFO  llm_load_print_meta: ssm_dt_rank      = 0
 - llama_engine.cc:523
20250107 23:31:27.402054 UTC 902738 INFO  llm_load_print_meta: ssm_dt_b_c_rms   = 0
 - llama_engine.cc:523
20250107 23:31:27.402058 UTC 902738 INFO  llm_load_print_meta: model type       = 1B
 - llama_engine.cc:523
20250107 23:31:27.402065 UTC 902738 INFO  llm_load_print_meta: model ftype      = Q8_0
 - llama_engine.cc:523
20250107 23:31:27.402070 UTC 902738 INFO  llm_load_print_meta: model params     = 1.24 B
 - llama_engine.cc:523
20250107 23:31:27.402075 UTC 902738 INFO  llm_load_print_meta: model size       = 1.22 GiB (8.50 BPW) 
 - llama_engine.cc:523
20250107 23:31:27.402079 UTC 902738 INFO  llm_load_print_meta: general.name     = Llama 3.2 1B Instruct
 - llama_engine.cc:523
20250107 23:31:27.402084 UTC 902738 INFO  llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
 - llama_engine.cc:523
20250107 23:31:27.402088 UTC 902738 INFO  llm_load_print_meta: EOS token        = 128009 '<|eot_id|>'
 - llama_engine.cc:523
20250107 23:31:27.402093 UTC 902738 INFO  llm_load_print_meta: EOT token        = 128009 '<|eot_id|>'
 - llama_engine.cc:523
20250107 23:31:27.402097 UTC 902738 INFO  llm_load_print_meta: EOM token        = 128008 '<|eom_id|>'
 - llama_engine.cc:523
20250107 23:31:27.402101 UTC 902738 INFO  llm_load_print_meta: LF token         = 128 'Ä'
 - llama_engine.cc:523
20250107 23:31:27.402106 UTC 902738 INFO  llm_load_print_meta: EOG token        = 128008 '<|eom_id|>'
 - llama_engine.cc:523
20250107 23:31:27.402110 UTC 902738 INFO  llm_load_print_meta: EOG token        = 128009 '<|eot_id|>'
 - llama_engine.cc:523
20250107 23:31:27.402115 UTC 902738 INFO  llm_load_print_meta: max token length = 256
 - llama_engine.cc:523
20250107 23:31:27.476146 UTC 902738 INFO  llm_load_tensors: offloading 16 repeating layers to GPU
 - llama_engine.cc:523
20250107 23:31:27.476176 UTC 902738 INFO  llm_load_tensors: offloading output layer to GPU
 - llama_engine.cc:523
20250107 23:31:27.476182 UTC 902738 INFO  llm_load_tensors: offloaded 17/17 layers to GPU
 - llama_engine.cc:523
20250107 23:31:27.476191 UTC 902738 INFO  llm_load_tensors:   CPU_Mapped model buffer size =   266.16 MiB
 - llama_engine.cc:523
20250107 23:31:27.476197 UTC 902738 INFO  llm_load_tensors:        CUDA0 model buffer size =  1252.41 MiB
 - llama_engine.cc:523
20250107 23:31:27.476221 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.570887 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.581153 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.586996 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.592915 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.603163 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.609050 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.615127 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.625176 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.631631 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.637472 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.647542 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.653610 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.659453 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.670036 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.675929 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.681767 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.685862 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.692005 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.698364 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.704806 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.709057 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.714904 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.720737 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.726636 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.730939 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.737175 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.743049 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.749053 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.753126 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.759121 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.764986 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.770801 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.773266 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.780594 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.786383 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.792181 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.794621 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.801933 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.807727 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.813516 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.815504 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.823294 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.829078 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.834863 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.836395 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.844603 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.850414 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.856207 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.857749 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.865976 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.871871 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.877857 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.879430 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.887666 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.893468 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.899288 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.900827 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.909043 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.914830 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.947058 UTC 902738 INFO  . - llama_engine.cc:523
20250107 23:31:27.947093 UTC 902738 INFO  
 - llama_engine.cc:523
20250107 23:31:27.958213 UTC 902738 INFO  llama_new_context_with_model: n_seq_max     = 4
 - llama_engine.cc:523
20250107 23:31:27.958230 UTC 902738 INFO  llama_new_context_with_model: n_ctx         = 8192
 - llama_engine.cc:523
20250107 23:31:27.958240 UTC 902738 INFO  llama_new_context_with_model: n_ctx_per_seq = 2048
 - llama_engine.cc:523
20250107 23:31:27.958246 UTC 902738 INFO  llama_new_context_with_model: n_batch       = 2048
 - llama_engine.cc:523
20250107 23:31:27.958251 UTC 902738 INFO  llama_new_context_with_model: n_ubatch      = 2048
 - llama_engine.cc:523
20250107 23:31:27.958256 UTC 902738 INFO  llama_new_context_with_model: flash_attn    = 1
 - llama_engine.cc:523
20250107 23:31:27.958264 UTC 902738 INFO  llama_new_context_with_model: freq_base     = 500000.0
 - llama_engine.cc:523
20250107 23:31:27.958271 UTC 902738 INFO  llama_new_context_with_model: freq_scale    = 1
 - llama_engine.cc:523
20250107 23:31:27.958277 UTC 902738 WARN  llama_new_context_with_model: n_ctx_per_seq (2048) < n_ctx_train (131072) -- the full capacity of the model will not be utilized
 - llama_engine.cc:521
20250107 23:31:27.965943 UTC 902738 INFO  llama_kv_cache_init:      CUDA0 KV buffer size =   256.00 MiB
 - llama_engine.cc:523
20250107 23:31:27.965962 UTC 902738 INFO  llama_new_context_with_model: KV self size  =  256.00 MiB, K (f16):  128.00 MiB, V (f16):  128.00 MiB
 - llama_engine.cc:523
20250107 23:31:27.966823 UTC 902738 INFO  llama_new_context_with_model:  CUDA_Host  output buffer size =     1.96 MiB
 - llama_engine.cc:523
20250107 23:31:27.967488 UTC 902738 ERROR ggml_backend_cuda_buffer_type_alloc_buffer: allocating 1018.00 MiB on device 0: cudaMalloc failed: out of memory
 - llama_engine.cc:517
20250107 23:31:27.967507 UTC 902738 ERROR ggml_gallocr_reserve_n: failed to allocate CUDA0 buffer of size 1067450368
 - llama_engine.cc:517
20250107 23:31:27.974446 UTC 902738 ERROR ggml_backend_cuda_buffer_type_alloc_buffer: allocating 1018.00 MiB on device 0: cudaMalloc failed: out of memory
 - llama_engine.cc:517
20250107 23:31:27.974492 UTC 902738 ERROR ggml_gallocr_reserve_n: failed to allocate CUDA0 buffer of size 1067450368
 - llama_engine.cc:517
20250107 23:31:27.974499 UTC 902738 ERROR llama_new_context_with_model: failed to allocate compute buffers
 - llama_engine.cc:517
20250107 23:31:28.059246 UTC 902738 ERROR Error loading the model - llama_engine.cc:687
ma.cpp unable to load model","model":"/MY_AI_MODELS_PATH/Llama-3.2-1B-Instruct-Q8_0.gguf"}
```
</details>

**Comment by phansel** [comment]
```
INFO  llama_load_model_from_file: using device CUDA0 (NVIDIA {MODEL}) - 1955 MiB free
--------
ERROR ggml_backend_cuda_buffer_type_alloc_buffer: allocating 1018.00 MiB on device 0: cudaMalloc failed: out of memory
ERROR ggml_backend_cuda_buffer_type_alloc_buffer: allocating 1018.00 MiB on device 0: cudaMalloc failed: out of memory
```
It looks like there are two attempts to allocate 1018 MiB. You won't be able to allocate 2036 MiB on a GPU with only 1955 MiB of free memory. Try using a smaller context length, offloading fewer layers, or using a lower quantization.

**Comment by imtuyethan** [comment]
Looking at these logs, I can identify the key issue - it's a GPU memory (VRAM) allocation failure. Let me break down what happened:

1. The system tried to load the Llama 3.2 1B Instruct model (Q8_0 quantized version)
2. Initially, things were going well:
   - Successfully allocated 1252.41 MiB for the model on CUDA0
   - Successfully allocated 256.00 MiB for the KV cache

3. The critical error occurred when trying to allocate compute buffers:
```
ERROR ggml_backend_cuda_buffer_type_alloc_buffer: allocating 1018.00 MiB on device 0: cudaMalloc failed: out of memory
```

The system needed approximately 1018 MiB more for compute buffers but couldn't allocate it because the GPU ran out of memory.

Total memory needed was roughly:
- 1252 MiB (model) 
- 256 MiB (KV cache)
- 1018 MiB (compute buffers)
= ~2.5 GB VRAM

To fix this, you could:
1. Free up GPU memory by closing other applications
2. Reduce the context length (currently set to 8192)
3. Try running with fewer GPU layers
4. Use CPU only mode if GPU memory is consistently an issue

Looks like you're having a NVIDIA GPU. It might be helpful to know your GPU model and total VRAM to better diagnose the issue. Please reopen the issue if it persists.

**Comment by oleole39** [comment]
Thank to both of you for the help!

GPU model "boasts" 2048mb VRAM on the paper, which are also displayed with `nvidia-smi` (cf. below). But it seems Jan sees only 1955 MiB available (as shown in the log extract in @phansel's post). Any way, it is fully available to Jan (apart form those 38MiB shown in `nvidia-smi` output that cannot be reduced I assume). 
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.120                Driver Version: 550.120        CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA {MODEL}                 Off |   00000000:02:00.0 Off |                  N/A |
| N/A   42C    P8             N/A / ERR!  |      39MiB /   2048MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      2009      G   /usr/lib/xorg/Xorg                              4MiB |
|    0   N/A  N/A     23061      C   ...ex-extension/dist/bin/cortex-server         32MiB |
+-----------------------------------------------------------------------------------------+

```

I went to the model's settings and tested changing a few params:
- changing GPU layers to 8 (when it defaults to 17) made the model load. 
- setting GPU layers to a slightly higher values was working too if lowering the context value.
- after what I deleted the thread and started a new one - I had to reapply manually the changes to have the model load. 
- after what I deleted the thread again and started a new one - now it was working with default param (context set to highest and GPU layers set to 17).

Somehow my issue is solved, but not sure what to understand in that!
