### ISSUE TITLE
bug: AMD GPU not Detected

### ISSUE THREAD

**Issue by Zuzzolo395** [janhq/jan#7341]
**Version:** Jan_0.7.5_x64

## Describe the bug
I just installed jan but it is not detecting my GPU (RX 6700 XT). It is using only my CPU and it's very slow

## Steps to Reproduce
Normal operation

## Expected behavior
GPU Recognised and application working faster

## Environment details

-     Operating System: Windows 11
-     Jan Version: 0.7.5
-     Processor: AMD Ryzen 5 4500
-     RAM: 16GB
-     GPU: AMD Radeon RX 6700 XT 12GB

**Comment by Zuzzolo395** [comment]
Thanks to the help on discord I found the answer, for any future user that may find this issue this is the fix that worked for me.

Download from [**here**](https://github.com/janhq/llama.cpp/releases/tag/b7261) (latest version at the time of writing) the vulkan backend for windows.

Navigate in the Jan app to the settings->model providers->Llama.cpp->"install backend from file", then select the downloaded file, and then it should recognize the gpu. 

If it doesn't you may need to download the Vulkan Runtime from [here](https://vulkan.lunarg.com/sdk/home).

**Comment by ks202005** [comment]
I had the same issue, but under ```settings->model providers->Llama.cpp``` I had to be sure to select ```b7261/win-vulkan-x64``` after installing the backend from the file ```llama-b7261-bin-win-vulkan-x64.tar.gz ```. I just assumed that when I hit "install backend from file" that it would automatically select it after installing. My RX 580 8 GB appears just under the "Hardware" section of the settings now.
