### ISSUE TITLE
bug: Download Failed - llamacpp-b8795-win-avx-cuda-cu12-0-x64

### ISSUE THREAD

**Issue by Lambreket** [janhq/jan#8090]
Version:
0.7.9

Describe the Bug:
Jan AI fails to download the llama.cpp CUDA backend and does not detect GPU.

Error:
Download Failed - llamacpp-b8795-win-avx-cuda-cu12-0-x64

Because of this, models cannot run.
Also, in Hardware settings GPU is not detected, even though NVIDIA GPU is installed and working (nvidia-smi works).

Steps to Reproduce:

Install and launch Jan AI
Select any model
Try to run it or send a prompt
Backend download starts and fails

Screenshots / Logs:

<img width="365" height="106" alt="Image" src="https://github.com/user-attachments/assets/9917a1f8-3b67-4d59-b879-428f2ac991ed" />

Operating System:
Windows

**Comment by Butterfliege99** [comment]
Hi i want do confirm the Error Lambreket described, i have the same problem with the Linux Flatpack version

**Version:**
0.7.9

**Describe the Bug:**
Jan AI fails to download llamacpp-b8795-linux-avx-cuda-cu12-0-x64 and does not detect GPU.

**Error:**
Download Failed - llamacpp-b8795-linux-avx-cuda-cu12-0-x64

Because of this, models cannot run.
Also, in Hardware settings GPU is not detected, even though NVIDIA GPU is installed and working

**Steps to Reproduce:**

Install and launch Jan AI
Select any model
Try to run it or send a prompt
Backend download starts and fails

**Screenshots / Logs:**
Error Message:

<img width="441" height="151" alt="Image" src="https://github.com/user-attachments/assets/03999404-c6ad-4aae-aa60-1153bdcda600" />

Not detected Graphic Card:

<img width="601" height="160" alt="Image" src="https://github.com/user-attachments/assets/319f85f9-e47e-4111-bd44-27aa8ba8531e" />



**Log:**
<details>
<summary>Terminal Log details</summary>
`Gtk-Message: 13:43:36.585: Failed to load module "xapp-gtk3-module"

** (Jan:2): WARNING **: 13:43:36.775: Disabled hardware acceleration because GTK failed to initialize GL: Keine verfügbaren Konfigurationen für das gegebene RGBA-Pixelformat.
[2026-04-26][11:43:36][app_lib::core::setup][INFO] Installing extensions. Clean up: false
[2026-04-26][11:43:36][app_lib::core::mcp::helpers][INFO] Starting MCP server exa (Initial attempt)
[2026-04-26][11:43:36][reqwest::connect][DEBUG] starting new connection: https://mcp.exa.ai/
[2026-04-26][11:43:36][app_lib::core::setup][INFO] jan CLI installed to /home/username/.local/bin/jan
[2026-04-26][11:43:36][app_lib::core::setup][INFO] XDG Desktop Portal theme listener active
[2026-04-26][11:43:37][app_lib::core::mcp::helpers][INFO] Connected to server: Some(InitializeResult { protocol_version: ProtocolVersion("2025-03-26"), capabilities: ServerCapabilities { experimental: None, logging: None, completions: Some({}), prompts: Some(PromptsCapability { list_changed: Some(true) }), resources: Some(ResourcesCapability { subscribe: None, list_changed: Some(true) }), tools: Some(ToolsCapability { list_changed: Some(true) }) }, server_info: Implementation { name: "mcp-typescript server on vercel", title: None, version: "0.1.0", icons: None, website_url: None }, instructions: None })
[2026-04-26][11:43:37][app_lib::core::mcp::helpers][INFO] MCP server exa started successfully
[2026-04-26][11:43:37][app_lib::core::mcp::helpers][INFO] MCP server exa initialized successfully
[2026-04-26][11:43:37][app_lib::core::mcp::helpers][INFO] MCP server initialization complete: 1 successful, 0 failed
[2026-04-26][11:43:38][app_lib::core::extensions::commands][INFO] get jan extensions, path: "/home/username/.var/app/ai.jan.Jan/data/Jan/data/extensions/extensions.json"
[VectorDB] Checking ANN availability...
[VectorDB] Trying 3 bundled paths...
[VectorDB]   Trying: ./src-tauri/resources/bin/sqlite-vec
[VectorDB]   Trying: ./resources/bin/sqlite-vec
[VectorDB]   Trying: /app/bin/resources/bin/sqlite-vec
[VectorDB] ✗ Failed to load sqlite-vec from all paths
[VectorDB] ANN status: NOT AVAILABLE ✗
[2026-04-26][11:43:38][tauri_plugin_hardware::vendor::nvidia][DEBUG] NVML initialized successfully
[2026-04-26][11:43:38][reqwest::connect][DEBUG] starting new connection: https://api.github.com/
[2026-04-26][11:43:39][tauri_plugin_llamacpp::gguf::commands][INFO] modelSize: 8133226464
[2026-04-26][11:43:39][reqwest::connect][DEBUG] starting new connection: https://api.github.com/
[2026-04-26][11:43:39][app_lib::core::updater::custom_updater][INFO] Checking for updates (current version: 0.7.9, 2 endpoints configured)
[2026-04-26][11:43:39][app_lib::core::updater::custom_updater][INFO] Trying primary endpoint with signing: https://apps.jan.ai/update-check
[2026-04-26][11:43:39][reqwest::connect][DEBUG] starting new connection: https://apps.jan.ai/
[2026-04-26][11:43:41][app_lib::core::updater::custom_updater][INFO] Successfully fetched update info from endpoint https://apps.jan.ai/update-check: version 0.7.9
[2026-04-26][11:43:41][app_lib::core::updater::commands][INFO] No update needed: current 0.7.9 is up to date with latest 0.7.9
[2026-04-26][11:43:41][tauri_plugin_updater::updater][DEBUG] checking for updates https://apps.jan.ai/update-check
[2026-04-26][11:43:41][reqwest::connect][DEBUG] starting new connection: https://apps.jan.ai/
[2026-04-26][11:43:41][tauri_plugin_updater::updater][DEBUG] update response: Object {"notes": String(""), "platforms": Object {"darwin-aarch64": Object {"signature": String("dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVSRXJUVWE2ekJCTHRVU1Q1TlF6VDBsNy9mN3NNVkVYbkZ3dm1ic0xYTW5NeHcrVzFnK0t2SjFDd2lFeEJTZnpHQWpNVGY5Y2d0U0twR3ozWDI3RW9LZjRqUGRFYzczNkE0PQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzc0MjMxOTM2CWZpbGU6SmFuLmFwcC50YXIuZ3oKTnRQSDJoUFdHQjEwME5nR2c1YllIMURpTWtwZ1daYytqeDRML1YzUllhVEw4UW02YzEzdjlCSUZwbkNkR3l5Q3ZBL3NuOWFUaDVmTUYxbk1KNHIrQ3c9PQo="), "url": String("https://github.com/janhq/jan/releases/download/v0.7.9/Jan.app.tar.gz")}, "darwin-x86_64": Object {"signature": String("dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVSRXJUVWE2ekJCTHRVU1Q1TlF6VDBsNy9mN3NNVkVYbkZ3dm1ic0xYTW5NeHcrVzFnK0t2SjFDd2lFeEJTZnpHQWpNVGY5Y2d0U0twR3ozWDI3RW9LZjRqUGRFYzczNkE0PQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzc0MjMxOTM2CWZpbGU6SmFuLmFwcC50YXIuZ3oKTnRQSDJoUFdHQjEwME5nR2c1YllIMURpTWtwZ1daYytqeDRML1YzUllhVEw4UW02YzEzdjlCSUZwbkNkR3l5Q3ZBL3NuOWFUaDVmTUYxbk1KNHIrQ3c9PQo="), "url": String("https://github.com/janhq/jan/releases/download/v0.7.9/Jan.app.tar.gz")}, "linux-x86_64": Object {"signature": String("dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVSRXJUVWE2ekJCTGhCK0ZvNDhjejk4WEczMTZadVcxQ2hWbnh5THAyWEdpclFtcGs1b1cyOTFNSlpuYVorSnJBTFp6QXFKTUhLbXUzajMzdWZkUFpxQi9YK2tXSlBEaWdjPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzc0MjMwNTgyCWZpbGU6SmFuXzAuNy45X2FtZDY0LkFwcEltYWdlCm5jRWRnUFRZcUdjQVhwU1cya3pIMjdVTjNtTE1CUVlTbzFZdHladDRCMHZYeTJWWXdLNk9uOS9kYXVSKzErT3JueDhWeXRIR3IrOVRGWlpDMFI4WkN3PT0K"), "url": String("https://github.com/janhq/jan/releases/download/v0.7.9/Jan_0.7.9_amd64.AppImage")}, "windows-x86_64": Object {"signature": String("dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVSRXJUVWE2ekJCTG1yZTlTeG02QjZCNC8zOEdYandpY3hMaDlMU1BicHNubWQvTTd6OGlMY1FiNDhieFJacUoyWGZFNFJkcDJuZzZ0blQ1YmFya3RnRnlQa1JVUm1VQVFZPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzc0MjMxMzI4CWZpbGU6SmFuXzAuNy45X3g2NC1zZXR1cC5leGUKT2U2ZTdEbmg0Q2thYi9XWGJBUkQ2akJxOFhNenhDbnA5Z3VsU0ROUys4UFhtQmJ4dEgzSzB2QzFEMXlQejFKV0hJRmVWYjkwYXg3bExVUDM3V2ppQVE9PQo="), "url": String("https://github.com/janhq/jan/releases/download/v0.7.9/Jan_0.7.9_x64-setup.exe")}}, "pub_date": String("2026-03-23T02:12:52.944Z"), "version": String("0.7.9")}
[2026-04-26][11:43:41][tauri_plugin_updater::updater][DEBUG] parsed release response RemoteRelease { version: Version { major: 0, minor: 7, patch: 9 }, notes: Some(""), pub_date: Some(2026-03-23 2:12:52.944 +00:00:00), data: Static { platforms: {"windows-x86_64": ReleaseManifestPlatform { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("github.com")), port: None, path: "/janhq/jan/releases/download/v0.7.9/Jan_0.7.9_x64-setup.exe", query: None, fragment: None }, signature: "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVSRXJUVWE2ekJCTG1yZTlTeG02QjZCNC8zOEdYandpY3hMaDlMU1BicHNubWQvTTd6OGlMY1FiNDhieFJacUoyWGZFNFJkcDJuZzZ0blQ1YmFya3RnRnlQa1JVUm1VQVFZPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzc0MjMxMzI4CWZpbGU6SmFuXzAuNy45X3g2NC1zZXR1cC5leGUKT2U2ZTdEbmg0Q2thYi9XWGJBUkQ2akJxOFhNenhDbnA5Z3VsU0ROUys4UFhtQmJ4dEgzSzB2QzFEMXlQejFKV0hJRmVWYjkwYXg3bExVUDM3V2ppQVE9PQo=" }, "darwin-aarch64": ReleaseManifestPlatform { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("github.com")), port: None, path: "/janhq/jan/releases/download/v0.7.9/Jan.app.tar.gz", query: None, fragment: None }, signature: "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVSRXJUVWE2ekJCTHRVU1Q1TlF6VDBsNy9mN3NNVkVYbkZ3dm1ic0xYTW5NeHcrVzFnK0t2SjFDd2lFeEJTZnpHQWpNVGY5Y2d0U0twR3ozWDI3RW9LZjRqUGRFYzczNkE0PQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzc0MjMxOTM2CWZpbGU6SmFuLmFwcC50YXIuZ3oKTnRQSDJoUFdHQjEwME5nR2c1YllIMURpTWtwZ1daYytqeDRML1YzUllhVEw4UW02YzEzdjlCSUZwbkNkR3l5Q3ZBL3NuOWFUaDVmTUYxbk1KNHIrQ3c9PQo=" }, "darwin-x86_64": ReleaseManifestPlatform { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("github.com")), port: None, path: "/janhq/jan/releases/download/v0.7.9/Jan.app.tar.gz", query: None, fragment: None }, signature: "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVSRXJUVWE2ekJCTHRVU1Q1TlF6VDBsNy9mN3NNVkVYbkZ3dm1ic0xYTW5NeHcrVzFnK0t2SjFDd2lFeEJTZnpHQWpNVGY5Y2d0U0twR3ozWDI3RW9LZjRqUGRFYzczNkE0PQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzc0MjMxOTM2CWZpbGU6SmFuLmFwcC50YXIuZ3oKTnRQSDJoUFdHQjEwME5nR2c1YllIMURpTWtwZ1daYytqeDRML1YzUllhVEw4UW02YzEzdjlCSUZwbkNkR3l5Q3ZBL3NuOWFUaDVmTUYxbk1KNHIrQ3c9PQo=" }, "linux-x86_64": ReleaseManifestPlatform { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("github.com")), port: None, path: "/janhq/jan/releases/download/v0.7.9/Jan_0.7.9_amd64.AppImage", query: None, fragment: None }, signature: "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVSRXJUVWE2ekJCTGhCK0ZvNDhjejk4WEczMTZadVcxQ2hWbnh5THAyWEdpclFtcGs1b1cyOTFNSlpuYVorSnJBTFp6QXFKTUhLbXUzajMzdWZkUFpxQi9YK2tXSlBEaWdjPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzc0MjMwNTgyCWZpbGU6SmFuXzAuNy45X2FtZDY0LkFwcEltYWdlCm5jRWRnUFRZcUdjQVhwU1cya3pIMjdVTjNtTE1CUVlTbzFZdHladDRCMHZYeTJWWXdLNk9uOS9kYXVSKzErT3JueDhWeXRIR3IrOVRGWlpDMFI4WkN3PT0K" }} } }
[2026-04-26][11:43:42][tauri_plugin_llamacpp::gguf::commands][INFO] Using ctx_size: 8192
[2026-04-26][11:43:42][tauri_plugin_llamacpp::gguf::utils][INFO] Received ctx_size parameter: Some(8192)
[2026-04-26][11:43:42][tauri_plugin_llamacpp::gguf::utils][INFO] KV estimates -> sliding: 88080384 bytes (~84.00 MB), full: 1409286144 bytes (~1344.00 MB), middle: 748683264 bytes (~714.00 MB)
[2026-04-26][11:43:42][tauri_plugin_llamacpp::gguf::commands][INFO] isModelSupported: Total memory requirement: 8881909728 for /home/username/.var/app/ai.jan.Jan/data/Jan/data/llamacpp/models/Gemma-4-E4B-Uncensored-HauhauCS-Aggressive-Q8_K_P/model.gguf; Got kvCacheSize: 748683264 from BE
[2026-04-26][11:43:42][tauri_plugin_llamacpp::gguf::commands][INFO] Total VRAM reported/calculated (in bytes): 27287093248
[2026-04-26][11:43:42][tauri_plugin_llamacpp::gguf::commands][INFO] System RAM: 33518780416 bytes
[2026-04-26][11:43:42][tauri_plugin_llamacpp::gguf::commands][INFO] Total VRAM: 27287093248 bytes
[2026-04-26][11:43:42][tauri_plugin_llamacpp::gguf::commands][INFO] Usable total memory: 56228893286 bytes
[2026-04-26][11:43:42][tauri_plugin_llamacpp::gguf::commands][INFO] Usable VRAM: 24998603059 bytes
[2026-04-26][11:43:42][tauri_plugin_llamacpp::gguf::commands][INFO] Required: 8881909728 bytes
[2026-04-26][11:43:42][tauri_plugin_llamacpp::backend][INFO] Already at latest version: b8795 = b8795
[2026-04-26][11:43:42][tauri_plugin_llamacpp::backend][INFO] Determined best available backend: b8795/linux-avx-cuda-cu12.0-x64 (Category: "cuda-cu12.0")
[2026-04-26][11:43:42][webview:info@asset://localhost/%2Fhome%2Fusername%2F.var%2Fapp%2Fai.jan.Jan%2Fdata%2FJan%2Fdata%2Fextensions%2F%40janhq%2Fllamacpp-extension%2Fdist%2Findex.js:2035:7][INFO]  Using stored backend preference: b8795/linux-avx-cuda-cu12.0-x64
[2026-04-26][11:43:42][webview:info@asset://localhost/%2Fhome%2Fusername%2F.var%2Fapp%2Fai.jan.Jan%2Fdata%2FJan%2Fdata%2Fextensions%2F%40janhq%2Fllamacpp-extension%2Fdist%2Findex.js:2035:7][INFO]  Initial UI default for version_backend set to: b8795/linux-cuda-12-common_cpus-x64
[2026-04-26][11:43:42][webview:info@asset://localhost/%2Fhome%2Fusername%2F.var%2Fapp%2Fai.jan.Jan%2Fdata%2FJan%2Fdata%2Fextensions%2F%40janhq%2Fllamacpp-extension%2Fdist%2Findex.js:2035:7][INFO]  Installing initial backend: b8795/linux-avx-cuda-cu12.0-x64
[2026-04-26][11:43:42][webview:info@asset://localhost/%2Fhome%2Fusername%2F.var%2Fapp%2Fai.jan.Jan%2Fdata%2FJan%2Fdata%2Fextensions%2F%40janhq%2Fllamacpp-extension%2Fdist%2Findex.js:2035:7][INFO]  Backend b8795/linux-avx-cuda-cu12.0-x64 not installed, downloading...
[2026-04-26][11:43:42][app_lib::core::downloads::helpers][INFO] Start download task: llamacpp-b8795-linux-avx-cuda-cu12-0-x64
[2026-04-26][11:43:42][reqwest::connect][DEBUG] starting new connection: https://github.com/
[2026-04-26][11:43:42][reqwest::async_impl::client][DEBUG] redirecting 'https://github.com/janhq/llama.cpp/releases/download/b8795/llama-b8795-bin-linux-avx-cuda-cu12.0-x64.tar.gz' to 'https://release-assets.githubusercontent.com/github-production-release-asset/947118834/dfafb177-85b6-4dfe-8bd3-a09ddf5298ac?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-04-26T12%3A23%3A38Z&rscd=attachment%3B+filename%3Dllama-b8795-bin-linux-avx-cuda-cu12.0-x64.tar.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-04-26T11%3A22%3A55Z&ske=2026-04-26T12%3A23%3A38Z&sks=b&skv=2018-11-09&sig=jTkxzsr1iLz06ihSCfarW0If24sZPniAFQ0kVXp9Q30%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3NzIwNzQyMiwibmJmIjoxNzc3MjAzODIyLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.1syEMhnEGuw-7EnNYC6jU4XjWXZxXoXRGTV0j_CrLb8&response-content-disposition=attachment%3B%20filename%3Dllama-b8795-bin-linux-avx-cuda-cu12.0-x64.tar.gz&response-content-type=application%2Foctet-stream'
[2026-04-26][11:43:42][reqwest::connect][DEBUG] starting new connection: https://release-assets.githubusercontent.com/
[2026-04-26][11:43:42][reqwest::connect][DEBUG] starting new connection: https://github.com/
[2026-04-26][11:43:42][app_lib::core::downloads::helpers][INFO] Start download task: llamacpp-b8795-linux-avx-cuda-cu12-0-x64
[2026-04-26][11:43:42][reqwest::connect][DEBUG] starting new connection: https://catalog.jan.ai/
[2026-04-26][11:43:43][reqwest::connect][DEBUG] starting new connection: https://catalog.jan.ai/
[2026-04-26][11:56:24][reqwest::connect][DEBUG] starting new connection: https://mcp.exa.ai/
[2026-04-26][11:56:24][tauri_plugin_llamacpp::gguf::commands][INFO] modelSize: 8133226464
[2026-04-26][11:56:25][webview:info@asset://localhost/%2Fhome%2Fusername%2F.var%2Fapp%2Fai.jan.Jan%2Fdata%2FJan%2Fdata%2Fextensions%2F%40janhq%2Fllamacpp-extension%2Fdist%2Findex.js:2035:7][INFO]  Backend b8795/linux-avx-cuda-cu12.0-x64 not installed, downloading...
[2026-04-26][11:56:25][app_lib::core::downloads::helpers][INFO] Start download task: llamacpp-b8795-linux-avx-cuda-cu12-0-x64
[2026-04-26][11:56:25][reqwest::connect][DEBUG] starting new connection: https://github.com/
[2026-04-26][11:56:25][reqwest::async_impl::client][DEBUG] redirecting 'https://github.com/janhq/llama.cpp/releases/download/b8795/llama-b8795-bin-linux-avx-cuda-cu12.0-x64.tar.gz' to 'https://release-assets.githubusercontent.com/github-production-release-asset/947118834/dfafb177-85b6-4dfe-8bd3-a09ddf5298ac?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-04-26T12%3A46%3A30Z&rscd=attachment%3B+filename%3Dllama-b8795-bin-linux-avx-cuda-cu12.0-x64.tar.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-04-26T11%3A45%3A52Z&ske=2026-04-26T12%3A46%3A30Z&sks=b&skv=2018-11-09&sig=i2fuwyae8l%2FHr0Av2B0G9JJ388XxMVRG3T2ST4%2BKryM%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3NzIwODE4NSwibmJmIjoxNzc3MjA0NTg1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.EyEP9cfABoOUuwQJGXqwejUdsKFH4V-78TEbUq_1XlQ&response-content-disposition=attachment%3B%20filename%3Dllama-b8795-bin-linux-avx-cuda-cu12.0-x64.tar.gz&response-content-type=application%2Foctet-stream'
[2026-04-26][11:56:25][reqwest::connect][DEBUG] starting new connection: https://release-assets.githubusercontent.com/
[2026-04-26][11:56:25][reqwest::connect][DEBUG] starting new connection: https://github.com/
[2026-04-26][11:56:26][app_lib::core::downloads::helpers][INFO] Start download task: llamacpp-b8795-linux-avx-cuda-cu12-0-x64
[2026-04-26][11:56:26][reqwest::connect][DEBUG] starting new connection: https://catalog.jan.ai/
[2026-04-26][11:56:26][reqwest::connect][DEBUG] starting new connection: https://catalog.jan.ai/
[2026-04-26][11:56:26][tauri_plugin_llamacpp::gguf::commands][INFO] Using ctx_size: 8192
[2026-04-26][11:56:26][tauri_plugin_llamacpp::gguf::utils][INFO] Received ctx_size parameter: Some(8192)
[2026-04-26][11:56:26][tauri_plugin_llamacpp::gguf::utils][INFO] KV estimates -> sliding: 88080384 bytes (~84.00 MB), full: 1409286144 bytes (~1344.00 MB), middle: 748683264 bytes (~714.00 MB)
[2026-04-26][11:56:26][tauri_plugin_llamacpp::gguf::commands][INFO] isModelSupported: Total memory requirement: 8881909728 for /home/username/.var/app/ai.jan.Jan/data/Jan/data/llamacpp/models/Gemma-4-E4B-Uncensored-HauhauCS-Aggressive-Q8_K_P/model.gguf; Got kvCacheSize: 748683264 from BE
[2026-04-26][11:56:26][tauri_plugin_llamacpp::gguf::commands][INFO] Total VRAM reported/calculated (in bytes): 27287093248
[2026-04-26][11:56:26][tauri_plugin_llamacpp::gguf::commands][INFO] System RAM: 33518780416 bytes
[2026-04-26][11:56:26][tauri_plugin_llamacpp::gguf::commands][INFO] Total VRAM: 27287093248 bytes
[2026-04-26][11:56:26][tauri_plugin_llamacpp::gguf::commands][INFO] Usable total memory: 56228893286 bytes
[2026-04-26][11:56:26][tauri_plugin_llamacpp::gguf::commands][INFO] Usable VRAM: 24998603059 bytes
[2026-04-26][11:56:26][tauri_plugin_llamacpp::gguf::commands][INFO] Required: 8881909728 bytes
`


</details>

**Operating System:**
Linux

**Comment by Butterfliege99** [comment]
### Working llamacpp Version
I have selected b8795/linux-avx-x64 as backend. the download worked and so does Jan-v3.5-4B-Q4_K_XL ( other Models not tested yet ) but the Graphic Card is still not recognized.
Its not fast but it works.


### Lists of other llamcpp download and GPU recognition Issues

#### I have found some other Issue Reports about llamacpp download problem so it seems to affect some more people.


**List by llamacpp Version:**


llamacpp-b7261-linux-vulkan-common_cups-x64 #7358 
llamacpp-b8783 #8005 
llamacpp-b8795-linux-avx-cuda-cu12-0-x64 #8005 
llamacpp-b8795-win-avx-cuda-cu12-0-x64 #8090



**List by Date:**
2026-01-16 Linux AppImage bug: llamacpp-b7261-linux-vulkan-common_cups-x64 download failed #7358 
2026-04-xx 0.7.9 via Flatpak Failed to detect GPU #8005 
2026-04-25 bug: Download Failed - llamacpp-b8795-win-avx-cuda-cu12-0-x64 #8090




#### Also the GPU recognition Problem seems so affect others.

**List by Jan version**

0.7.2 GPU recognized, mentioned in #6999
0.7.3 GPU not recognized, (NVIDIA CUDA) #6999
0.7.7 GPU not recognized [NVIDIA GeForce GTX 1080] #7553 
0.7.9 GPU not recognized #8005 

**List by Date**



2025-11-08 GPU not recognized after factory reset  #6992 no Jan Version mentioned 
2025-11-18 GPU (NVIDIA CUDA) not recognised on latest jan 0.73 #6999 Version 0.73  Version 0.7.2 working
2026-02-24 No GPU detected but Nvidia GTX 1080 installed #7553 
2026-04-xx 0.7.9 via Flatpak Failed to detect GPU #8005
2026-04-24 Jan is not detecting my GPUs #8053 no Jan Version mentioned 



##### Maybe this helps for a little overview - if not please delete

**Comment by pastukhvladyslav** [comment]
I was getting the same download error issue for `b8795`. The new version `b8892` was downloaded successfully, but GPU is not found. To be more specific I use this version:
- `b8892/linux-cuda-13-common_cpus-x64`
- installed via flatpak

Now I can fit models only into RAM.

**Comment by silviyahasana** [comment]
@pastukhvladyslav hi, I came across the same issue with b8892 using the deb version. The error was not "_failed to fetch device_" but "_llama backend could not be loaded_" or something. I checked my log files and turned out the `libnccl` was not found.

`llama-server: error while loading shared libraries: libnccl.so.2: cannot open shared object file: No such file or directory`

From here, obviously it is straightforward. I installed nvcc and the problem is gone. So please include your logs too, just in case it is the same. I haven't managed to find a way to make Jan read my GPU with Flatpak version as well, in fact my bug report is also still open. But if it's urgent, you can try the deb version.

**Comment by HydroRaptor** [comment]
### Environment Details
- **OS:** Ubuntu 24.04 LTS
- **GPU:** NVIDIA GeForce RTX 5090 (Blackwell Architecture, Compute Capability 12.0)
- **CUDA Version:** 13.1.115
- **Jan Version:** 0.7.9
- **Bundled Engine Flavor:** `b8892/linux-cuda-13-common_cpus-x64`

### The Issue
The bundled `llama-server` binary returns an empty string under `Available devices:` because it lacks compilation mappings for Compute Capability 12.0 hardware configurations. Furthermore, `NVML` fails to link out-of-the-box due to a missing generic `libnvidia-ml.so` fallback pointer within `/usr/lib/x86_64-linux-gnu/`.

### How to Bypass / Temporary Fix
For users dealing with high-end Blackwell desktop environments, you can manually build a native, forward-compatible binary that hooks natively into the GUI:

1. **Fix the Driver Link:**

`sudo ln -s /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so`

2. **Compile b8892 Natively targeting host paths:**
```
git clone --branch b8892 --recurse-submodules [https://github.com/ggerganov/llama.cpp.git](https://github.com/ggerganov/llama.cpp.git)
cd llama.cpp
cmake -B build -DGGML_CUDA=ON
cmake --build build --config Release -j$(nproc)
```

3. **Package for Jan Parser Wrapper:**
```
mkdir -p ~/jan-native-backend/build/bin
cp build/bin/llama-server ~/jan-native-backend/build/bin/
cd ~/jan-native-backend
zip -r llama-b8892-bin-cuda13.zip build/
```
