### ISSUE TITLE
bug:  bug: Linux CUDA llama.cpp backends ship with hardcoded CI RUNPATH and unbundled libnccl, breaking GPU detection on Debian/Fedora/Arch

### ISSUE THREAD

**Issue by zssyntaxarchive** [janhq/jan#8145]
On a clean Debian Trixie install with a working NVIDIA driver (580.126.18) and CUDA toolkit (13.1), Jan's hardware detection reports "No devices found" even though nvidia-smi, vulkaninfo, and the system CUDA stack all work correctly. The GPU is an RTX 5070 Ti (Blackwell, sm_120).

Root cause is two upstream packaging defects in the bundled llama.cpp release b8892, variant linux-cuda-13-common_cpus-x64. These are reproducible on any Linux distro that isn't Ubuntu LTS with NVIDIA's libnccl preinstalled — likely affects #8123 (bazzite) as well.

## Steps to reproduce

1. Install Jan 0.7.9 via the .deb on Debian Trixie 13.4
2. Have a working NVIDIA stack (driver 580+, nvidia-smi works, /dev/nvidia* present, libcuda.so.1 in ldconfig cache)
3. Launch Jan; it auto-downloads backend b8892/linux-cuda-13-common_cpus-x64
4. Open Settings → Hardware

**Expected:** RTX 5070 Ti listed as a CUDA device.
**Actual:** No devices found.

## Diagnosis

Jan's logs show:

[tauri_plugin_hardware::vendor::nvidia][DEBUG] NVML initialized successfully
[tauri_plugin_llamacpp::backend][INFO] Determined best available backend:
b8892/linux-cuda-13-common_cpus-x64 (Category: "cuda-cu13.0")
[tauri_plugin_llamacpp::device][INFO] Device list output:
Available devices:
[tauri_plugin_llamacpp::device][WARN] No devices found in output

Running the bundled `llama-server --list-devices` directly (Jan swallows stderr):

llama-server: error while loading shared libraries: libllama-common.so.0:
cannot open shared object file: No such file or directory

...despite `libllama-common.so.0` sitting in the same directory.

## Bug 1: hardcoded CI RUNPATH on every ELF

$ patchelf --print-rpath llama-server
/home/runner/actions-runner/_work/llama.cpp/llama.cpp/build/bin:

All 24 binaries and shared libraries in the bundle have the GitHub Actions runner's build directory baked in as their RUNPATH instead of `$ORIGIN`. They can't find their siblings on any user's machine.

## Bug 2: libnccl.so.2 is a NEEDED dependency but not bundled

$ readelf -d libggml-cuda.so | grep NEEDED
0x0000000000000001 (NEEDED) Shared library: [libnccl.so.2]

`libnccl.so.2` is not present in the tarball and is not a default package on most distros (Debian has it in contrib, not main). Even after fixing Bug 1, `dlopen("libggml-cuda.so")` fails and llama.cpp silently falls back to CPU-only.

## Workaround that fixes both bugs

```bash
sudo apt install patchelf libnccl2   # Debian/Ubuntu; Fedora equivalent: patchelf + libnccl
DIR=~/.local/share/Jan/data/llamacpp/backends/b8892/linux-cuda-13-common_cpus-x64/build/bin
patchelf --set-rpath '$ORIGIN' "$DIR"/llama-{server,cli,bench}
for f in "$DIR"/*.so*; do
  [ -L "$f" ] && continue
  patchelf --set-rpath '$ORIGIN' "$f"
done
```

After this, llama-server correctly reports:

ggml_cuda_init: found 1 CUDA devices (Total VRAM: 15838 MiB):
Device 0: NVIDIA GeForce RTX 5070 Ti, compute capability 12.0, VMM: yes
load_backend: loaded CUDA backend from .../libggml-cuda.so

...and Jan's `getDevices` call returns the GPU normally.

## Proposed upstream fix

In the llama.cpp CUDA build CMake (or the janhq fork's build pipeline):

```cmake
set_target_properties(llama-server llama-cli llama-bench PROPERTIES
    INSTALL_RPATH "$ORIGIN"
    BUILD_WITH_INSTALL_RPATH TRUE
)
```

And either:
- Bundle `libnccl.so.2` in the tarball alongside the other CUDA libs, or
- Build with `-DGGML_CUDA_NO_NCCL=ON` (or equivalent) for single-GPU consumer builds, since NCCL is only used for multi-GPU collectives

## Environment

- **OS:** Debian Trixie 13.4, kernel 6.12.86+deb13-amd64
- **DE:** KDE Plasma on Xorg
- **GPU:** NVIDIA RTX 5070 Ti (Blackwell, sm_120)
- **NVIDIA driver:** 580.126.18
- **CUDA toolkit:** 13.1.80
- **Jan version:** 0.7.9 (installed via .deb)
- **Bundled llama.cpp backend:** b8892, variant linux-cuda-13-common_cpus-x64

## Related

- #8123 — "llama.cpp hardware backend not downloading on bazzite" likely related (Fedora-based, no libnccl in default repos)
- #8144 — "use llama-cpp from system" would sidestep this entire class of bug

**Comment by qnixsynapse** [comment]
I think the next version will provide a way to check for dependencies.

**Comment by HydroRaptor** [comment]
### Environment Details
- **OS:** Ubuntu 24.04 LTS
- **GPU:** NVIDIA GeForce RTX 5090 (Blackwell Architecture, Compute Capability 12.0)
- **CUDA Version:** 13.1.115
- **Jan Version:** 0.7.9
- **Bundled Engine Flavor:** `b8892/linux-cuda-13-common_cpus-x64`

### The Issue
The bundled `llama-server` binary returns an empty string under `Available devices:` because it lacks compilation mappings for Compute Capability 12.0 hardware configurations. Furthermore, `NVML` fails to link out-of-the-box due to a missing generic `libnvidia-ml.so` fallback pointer within `/usr/lib/x86_64-linux-gnu/`.

### How to Bypass / Temporary Fix
For users dealing with high-end Blackwell desktop environments, you can manually build a native, forward-compatible binary that hooks natively into the GUI:

1. **Fix the Driver Link:**

`sudo ln -s /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so`

2. **Compile b8892 Natively targeting host paths:**
```
git clone --branch b8892 --recurse-submodules [https://github.com/ggerganov/llama.cpp.git](https://github.com/ggerganov/llama.cpp.git)
cd llama.cpp
cmake -B build -DGGML_CUDA=ON
cmake --build build --config Release -j$(nproc)
```

3. **Package for Jan Parser Wrapper:**
```
mkdir -p ~/jan-native-backend/build/bin
cp build/bin/llama-server ~/jan-native-backend/build/bin/
cd ~/jan-native-backend
zip -r llama-b8892-bin-cuda13.zip build/
```

**Comment by awesomeshot5051** [comment]
> On a clean Debian Trixie install with a working NVIDIA driver (580.126.18) and CUDA toolkit (13.1), Jan's hardware detection reports "No devices found" even though nvidia-smi, vulkaninfo, and the system CUDA stack all work correctly. The GPU is an RTX 5070 Ti (Blackwell, sm_120).
> 
> Root cause is two upstream packaging defects in the bundled llama.cpp release b8892, variant linux-cuda-13-common_cpus-x64. These are reproducible on any Linux distro that isn't Ubuntu LTS with NVIDIA's libnccl preinstalled — likely affects [#8123](https://github.com/janhq/jan/issues/8123) (bazzite) as well.
> 
> ## Steps to reproduce
> 1. Install Jan 0.7.9 via the .deb on Debian Trixie 13.4
> 2. Have a working NVIDIA stack (driver 580+, nvidia-smi works, /dev/nvidia* present, libcuda.so.1 in ldconfig cache)
> 3. Launch Jan; it auto-downloads backend b8892/linux-cuda-13-common_cpus-x64
> 4. Open Settings → Hardware
> 
> **Expected:** RTX 5070 Ti listed as a CUDA device. **Actual:** No devices found.
> 
> ## Diagnosis
> Jan's logs show:
> 
> [tauri_plugin_hardware::vendor::nvidia][DEBUG] NVML initialized successfully [tauri_plugin_llamacpp::backend][INFO] Determined best available backend: b8892/linux-cuda-13-common_cpus-x64 (Category: "cuda-cu13.0") [tauri_plugin_llamacpp::device][INFO] Device list output: Available devices: [tauri_plugin_llamacpp::device][WARN] No devices found in output
> 
> Running the bundled `llama-server --list-devices` directly (Jan swallows stderr):
> 
> llama-server: error while loading shared libraries: libllama-common.so.0: cannot open shared object file: No such file or directory
> 
> ...despite `libllama-common.so.0` sitting in the same directory.
> 
> ## Bug 1: hardcoded CI RUNPATH on every ELF
> $ patchelf --print-rpath llama-server /home/runner/actions-runner/_work/llama.cpp/llama.cpp/build/bin:
> 
> All 24 binaries and shared libraries in the bundle have the GitHub Actions runner's build directory baked in as their RUNPATH instead of `$ORIGIN`. They can't find their siblings on any user's machine.
> 
> ## Bug 2: libnccl.so.2 is a NEEDED dependency but not bundled
> $ readelf -d libggml-cuda.so | grep NEEDED 0x0000000000000001 (NEEDED) Shared library: [libnccl.so.2]
> 
> `libnccl.so.2` is not present in the tarball and is not a default package on most distros (Debian has it in contrib, not main). Even after fixing Bug 1, `dlopen("libggml-cuda.so")` fails and llama.cpp silently falls back to CPU-only.
> 
> ## Workaround that fixes both bugs
> sudo apt install patchelf libnccl2   # Debian/Ubuntu; Fedora equivalent: patchelf + libnccl
> DIR=~/.local/share/Jan/data/llamacpp/backends/b8892/linux-cuda-13-common_cpus-x64/build/bin
> patchelf --set-rpath '$ORIGIN' "$DIR"/llama-{server,cli,bench}
> for f in "$DIR"/*.so*; do
>   [ -L "$f" ] && continue
>   patchelf --set-rpath '$ORIGIN' "$f"
> done
> After this, llama-server correctly reports:
> 
> ggml_cuda_init: found 1 CUDA devices (Total VRAM: 15838 MiB): Device 0: NVIDIA GeForce RTX 5070 Ti, compute capability 12.0, VMM: yes load_backend: loaded CUDA backend from .../libggml-cuda.so
> 
> ...and Jan's `getDevices` call returns the GPU normally.
> 
> ## Proposed upstream fix
> In the llama.cpp CUDA build CMake (or the janhq fork's build pipeline):
> 
> set_target_properties(llama-server llama-cli llama-bench PROPERTIES
>     INSTALL_RPATH "$ORIGIN"
>     BUILD_WITH_INSTALL_RPATH TRUE
> )
> And either:
> 
> * Bundle `libnccl.so.2` in the tarball alongside the other CUDA libs, or
> * Build with `-DGGML_CUDA_NO_NCCL=ON` (or equivalent) for single-GPU consumer builds, since NCCL is only used for multi-GPU collectives
> 
> ## Environment
> * **OS:** Debian Trixie 13.4, kernel 6.12.86+deb13-amd64
> * **DE:** KDE Plasma on Xorg
> * **GPU:** NVIDIA RTX 5070 Ti (Blackwell, sm_120)
> * **NVIDIA driver:** 580.126.18
> * **CUDA toolkit:** 13.1.80
> * **Jan version:** 0.7.9 (installed via .deb)
> * **Bundled llama.cpp backend:** b8892, variant linux-cuda-13-common_cpus-x64
> 
> ## Related
> * [bug: llama.cpp hardware backend not downloading on bazzite #8123](https://github.com/janhq/jan/issues/8123) — "llama.cpp hardware backend not downloading on bazzite" likely related (Fedora-based, no libnccl in default repos)
> * [idea: use llama-cpp from system #8144](https://github.com/janhq/jan/issues/8144) — "use llama-cpp from system" would sidestep this entire class of bug

This worked for me. Thank you man!

**Comment by giacomoferretti** [comment]
Using Jan installed via Flatpak on Fedora 43.

These are the commands I've used to fix this problem (thanks @zssyntaxarchive )

```bash
DIR=~/.var/app/ai.jan.Jan/data/Jan/data/llamacpp/backends/b9387/linux-cuda-13-common_cpus-x64/build/bin

# Bug 1
patchelf --set-rpath '$ORIGIN' "$DIR"/llama-server "$DIR"/llama-cli "$DIR"/llama-bench 2>/dev/null
for f in "$DIR"/*.so*; do
  [ -L "$f" ] && continue
  patchelf --set-rpath '$ORIGIN' "$f"
done

# Bug 2
cp "$(ldconfig -p | awk '/libnccl.so.2/{print $NF; exit}')" "$DIR"/
```

For `libnccl` had to install new repos that I was missing, didn't find the correct guides for it.

```bash
# cuda-toolkit (don't know if we need this, just sharing)
sudo dnf config-manager addrepo --from-repofile=https://developer.download.nvidia.com/compute/cuda/repos/fedora43/$(uname -m)/cuda-fedora43.repo
sudo dnf clean all
sudo dnf config-manager setopt cuda-fedora43-$(uname -m).exclude=nvidia-driver,nvidia-modprobe,nvidia-persistenced,nvidia-settings,nvidia-libXNVCtrl,nvidia-xconfig
sudo dnf install -y cuda-toolkit xorg-x11-drv-nvidia-cuda

# libnccl
sudo dnf config-manager addrepo --from-repofile=https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo
sudo dnf clean all
sudo dnf config-manager setopt cuda-rhel9-$(uname -m).exclude=nvidia-driver,nvidia-modprobe,nvidia-persistenced,nvidia-settings,nvidia-libXNVCtrl,nvidia-xconfig
sudo dnf install -y libnccl libnccl-devel
```

**Comment by yyyyyiiiiii** [comment]
> * `DGGML_CUDA_NO_NCCL=ON` (or equivalent) for single-GPU consumer builds, since NCCL is only used for multi-GPU collectives
> 
> 
> ## Environment

yeah, same thing, i just copied libnccl.so.2 from host and only after it detect gpu
